### ISSUE TITLE
Preciser le type d'oxygenotherapie (LN/Masque/MHC/FreeO2)

### ISSUE THREAD

**Issue by JMenguy** [ICUDYN/ICUDYN.jl#17]

**Comment by tencnivel** [comment]
à discuter

**Comment by JMenguy** [comment]
definitions: 
ventilation invasive = VAC, VSAI
ventilation non invasive = OHD, VNI, O2 (LN, masque, MHC, FreeO2)

soins intensifs (critical ventilation) = VAC, VSAI, OHD, VNI
soins non intensifs = O2 (LN, masque, MHC, FreeO2)

si soins non intensifs = O2 (LN, masque, MHC, FreeO2) > preciser le mode d'administration dans colonne "nonCriticalVentilType" . Colonne "Ventilation_criticalVentilType" reste vide

**Comment by tencnivel** [comment]
Récupérer les valeurs MaHT et FreeO2, LuN dans les données brutes

**Comment by BaptisteLaurent** [comment]
Proposition à discuter: réorganiser les données comme suit :

VentilType | Critical ? | Invasive ?
VAC           | True       | True
OHD          | True       | False
...               | ...           | ...

**Comment by tencnivel** [comment]
pas besoin
