### ISSUE TITLE
Enlever les valeurs debit O2 si ventilation VNI ou VS-AI uniquement

### ISSUE THREAD

**Issue by tencnivel** [ICUDYN/ICUDYN.jl#19]

**Comment by tencnivel** [comment]
On est pas intéressé par le debit si ventilation VNI ou VS/AI

**Comment by tencnivel** [comment]
Le débit est fixe pour le VNI et l'invasif

**Comment by BaptisteLaurent** [comment]
On prend finalement les débits en compte, car ils indiquent que le patient est sous O2 (même sur une courte période, avec alternance entre O2 et VNI/VS-AI).
